### ISSUE TITLE
The mapping only on scannet datasets aborted at a specific frame

### ISSUE THREAD

**Issue by laliwang** [SYSU-STAR/H2-Mapping#11]
When I run the code `python -W ignore demo/run_mapping.py configs/scannet/scene0059.yaml` at [GeForce RTX 3090], I notice that the mapping always interrupts unexpectedly at a certain frame. For example, scene0181 interrupts at 879th, scene 0059 interrupts at 1459th. The screenshots are shown as follows:
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/97450124/610403e1-2334-4707-9b89-b2e8650a2d08)

Although the error indicates that libgcc_s.so.1 cannnot be found when pthread_cancel is called, the mapping is not supposed to quit before finished. After I solve the error thrown by libgcc_s.so.1, the mapping still interrupts at the same frame without any errors.
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/97450124/a0c77041-d41f-4103-a03a-a66ba0cce3c5)

While for the mapping only on replica dataset, it can perform well untill finished.
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/97450124/df944ff3-8e32-4a7c-be0a-a65f0f595d90)

**Comment by JIANG-CX** [comment]
Apologies for the oversight. The reason is that the original ScanNet pose in this particular frame is inf. Consequently, I have excluded this invalid pose in the latest version. Thanks.

**Comment by laliwang** [comment]
Thank you for your modification, I ignore that the pose is potentially invalid.

**Comment by JIANG-CX** [comment]
o(*￣▽￣*)ブ
