### ISSUE TITLE
[Discuss]Is it possible to replace the RGBD camera with a LiDAR plus a camera?

### ISSUE THREAD

**Issue by ZorAttC** [SYSU-STAR/H2-Mapping#17]
Why do most works  use cameras and lidars for real-time 3D reconstruction？If a visible light camera and lidar with calibrated parameters are used to obtain point clouds with colors using methods such as r3live, will the reconstruction fail because the point cloud is too sparse?

为什么大多数工作都是用使用RGBD摄像头，如果将使用标定好外参的可见光摄像头和激光雷达，使用类似如r3live的方法获取带有颜色的点云，是否有可能使用摄像头和激光雷达进行实时三维重建？这样做会因为点云过于稀疏而失败吗？

**Comment by JIANG-CX** [comment]
> Why do most works use cameras and lidars for real-time 3D reconstruction？If a visible light camera and lidar with calibrated parameters are used to obtain point clouds with colors using methods such as r3live, will the reconstruction fail because the point cloud is too sparse?
> 
> 为什么大多数工作都是用使用RGBD摄像头，如果将使用标定好外参的可见光摄像头和激光雷达，使用类似如r3live的方法获取带有颜色的点云，是否有可能使用摄像头和激光雷达进行实时三维重建？这样做会因为点云过于稀疏而失败吗？

可能因为室内场景的话RGBD相机更简单方便，可以尝试一下使用标定好的相机和雷达进行重建
