### ISSUE TITLE
Do you have any plan to release this work?

### ISSUE THREAD

**Issue by tlok666** [SYSU-STAR/H2-Mapping#2]
Thanks for this interesting work. Would you be able to release the code?

**Comment by JIANG-CX** [comment]
> Thanks for this interesting work. Would you be able to release the code?

Thank you for your interest in our work. We plan to release the source code after the paper is accepted. Thank you.

**Comment by cv-lab-x** [comment]
> > Thanks for this interesting work. Would you be able to release the code?
> 
> Thank you for your interest in our work. We plan to release the source code after the paper is accepted. Thank you.

Hi, which conferences do you submit?

**Comment by JIANG-CX** [comment]
> > > Thanks for this interesting work. Would you be able to release the code?
> > 
> > 
> > Thank you for your interest in our work. We plan to release the source code after the paper is accepted. Thank you.
> 
> Hi, which conferences do you submit?

This paper is submitted to "IEEE Robotics and Automation Letters", and it is currently undergoing a review process.

**Comment by mattiapiz** [comment]
> > Thanks for this interesting work. Would you be able to release the code?
> 
> Thank you for your interest in our work. We plan to release the source code after the paper is accepted. Thank you.

Hi, any news? Very interesting work, I can not wait :)

**Comment by JIANG-CX** [comment]
Thanks for your interest. The code will be released at the end of this month. Thanks. From: ***@***.*** ***@***.***> on behalf of Mattia Pizzuto ***@***.***>Sent: Friday, September 15, 2023 17:01To: SYSU-STAR/H2-Mapping ***@***.***>Cc: JIANG Chenxing ***@***.***>; Comment ***@***.***>Subject: Re: [SYSU-STAR/H2-Mapping] Do you have any plan to release this work? (Issue #2) 
Hi, any news?


Thanks for this interesting work. Would you be able to release the code?

Thank you for your interest in our work. We plan to release the source code after the paper is accepted. Thank you.

Hi, any news? Very interesting work, I can not wait :)

**Comment by JIANG-CX** [comment]
> Hi, any news?
> 
> > > Thanks for this interesting work. Would you be able to release the code?
> > 
> > 
> > Thank you for your interest in our work. We plan to release the source code after the paper is accepted. Thank you.
> 
> Hi, any news? Very interesting work, I can not wait :)

Thanks for your interest. The code will be released at the end of this month. Thanks.
