### ISSUE TITLE
******* initializing first_frame: 0******** 段错误 (核心已转储)

### ISSUE THREAD

**Issue by orientwx** [SYSU-STAR/H2-Mapping#21]
(h2mapping) robot@re:~/slam/H2-Mapping/mapping$  python -W ignore demo/run_mapping.py configs/replica/room_0.yaml
******* initializing first_frame: 0********
段错误 (核心已转储)
   
在第一次运行这个命令“python -W ignore demo/run_mapping.py configs/replica/room_0.yaml”时
出现如下错误
“******* initializing first_frame: 0********
段错误 (核心已转储)” 是什么原因？

**Comment by JIANG-CX** [comment]
没有遇到过类似的问题，可以先看一下跑一下tinycudann上的样例，看tinycudann是否安装正常。

**Comment by orientwx** [comment]
> 没有遇到过类似的问题，可以先看一下跑一下tinycudann上的样例，看tinycudann是否安装正常。

你用的pytorch和cuda是什么版本的？

**Comment by orientwx** [comment]
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/136042129/be500088-f7c8-48e6-81b1-be79aa754549) 

libgcc_s.so.1 must be installed for pthread_cancel to work

现在又遇到这个问题😂

**Comment by JIANG-CX** [comment]
pytorch 1.13.0； CUDA 11.7
看报错，mapping的运行过程好像没有问题，你可以具体看一下是最后的哪一步会出错，比如保存ckpt？

**Comment by orientwx** [comment]
> pytorch 1.13.0； CUDA 11.7
> 
> 看报错，mapping的运行过程好像没有问题，你可以具体看一下是最后的哪一步会出错，比如保存ckpt？

多谢 已经解决了

**Comment by JIANG-CX** [comment]
ok
