### ISSUE TITLE
是最终生成的网格的缘故吗，为什么建图看起来效果没有视频里的好

### ISSUE THREAD

**Issue by orientwx** [SYSU-STAR/H2-Mapping#23]
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/136042129/179d4c35-fe00-48cf-9b81-b15889a8788b)![image](https://github.com/SYSU-STAR/H2-Mapping/assets/136042129/65118258-c09b-4426-b391-88b0a2d22e14)

**Comment by JIANG-CX** [comment]
视频中的mesh的shading选的是None，可以在meshlab右侧的shading处选择，谢谢

**Comment by orientwx** [comment]
解决了 谢谢😊
