### ISSUE TITLE
gazebo 自制数据集仿真出错

### ISSUE THREAD

**Issue by dyb678** [SYSU-STAR/H2-Mapping#31]
感谢您如此杰出的工作！我想请问一下在修改到用gazebo仿真重建的时候需要修改什么呢，我现在只修改了对应的topic名，并且camera_pose直接通过mavros/local_position/odom得到，目前仿真能够进行正常的接收到但是重建不对。
<img width="475" alt="微信图片_20240319000523" src="https://github.com/SYSU-STAR/H2-Mapping/assets/93396587/c0fcf0e6-d897-4908-b059-3357e6f0eb68">
我用您的数据集tower_compressed.bag能够正常重建
<img width="475" alt="微信图片_20240319000517" src="https://github.com/SYSU-STAR/H2-Mapping/assets/93396587/51678ab3-116c-4531-957d-b028a3c9ed94">
请问我是不是遗忘了重要的位置没有修改呢

**Comment by JIANG-CX** [comment]
请按照https://github.com/SYSU-STAR/H2-Mapping?tab=readme-ov-file#use-your-own-rgb-d-sequence进行设置，谢谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ybdai121 ***@***.***>
发送时间: Tuesday, March 19, 2024 12:08:11 AM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SYSU-STAR/H2-Mapping] gazebo 自制数据集仿真出错 (Issue #31)


感谢您如此杰出的工作！我想请问一下在修改到用gazebo仿真重建的时候需要修改什么呢，我现在只修改了对应的topic名，并且camera_pose直接通过mavros/local_position/odom得到，目前仿真能够进行正常的接收到但是重建不对。
_20240319000523.png (view on web)<https://github.com/SYSU-STAR/H2-Mapping/assets/93396587/c0fcf0e6-d897-4908-b059-3357e6f0eb68>
我用您的数据集tower_compressed.bag能够正常重建
_20240319000517.png (view on web)<https://github.com/SYSU-STAR/H2-Mapping/assets/93396587/51678ab3-116c-4531-957d-b028a3c9ed94>
请问我是不是遗忘了重要的位置没有修改呢

―

**Comment by dyb678** [comment]
非常感谢您神速的回复！问题已经得到解决，在gazebo中仿真输出的depth貌似是以m为单位的。
