### ISSUE TITLE
Regarding a question about the metrics used in the experiment

### ISSUE THREAD

**Issue by Ubee121** [SYSU-STAR/H2-Mapping#34]
Hello, I have a question about the metrics used in the experiment. For SSIM, PSNR, etc., does the term "extrapolate" mean that a new perspective is generated for calculation? If so, how is the GT (ground truth) color frame obtained? Is it included in your code? Thank you very much!

**Comment by JIANG-CX** [comment]
The GT color frame from extrapolated views is from the NICER-SLAM (https://github.com/cvg/nicer-slam?tab=readme-ov-file#extrapolation)
