### ISSUE TITLE
关于frame中pose offset的问题

### ISSUE THREAD

**Issue by LeonATP** [SYSU-STAR/H2-Mapping#36]
感谢您的工作，这里有个小地方不太懂，想找您请教一下，为什么在frame读取数据的时候需要：
```
self.ref_pose[:3, 3] += offset  # Offset ensures voxel coordinates>0
```
我这里不太理解的是为什么voxel的coordinates是必须都大于0的呢？不能像SLAM中的点出现负数的情况呢？

**Comment by JIANG-CX** [comment]
您好，这个主要是为了维护八叉树时候更加方便，比如构建莫顿编码的时候，和判断八叉树层级的时候。

________________________________
发件人: Zhongmiao Yan ***@***.***>
发送时间: Wednesday, June 19, 2024 9:32:37 PM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SYSU-STAR/H2-Mapping] 关于frame中pose offset的问题 (Issue #36)


感谢您的工作，这里有个小地方不太懂，想找您请教一下，为什么在frame读取数据的时候需要：

self.ref_pose[:3, 3] += offset  # Offset ensures voxel coordinates>0


我这里不太理解的是为什么voxel的coordinates是必须都大于0的呢？不能像SLAM中的点出现负数的情况呢？

―

**Comment by LeonATP** [comment]
好的，感谢您的及时回复！
