### ISSUE TITLE
A little question about eval_recon.py code

### ISSUE THREAD

**Issue by Ubee121** [SYSU-STAR/H2-Mapping#39]
I encountered some minor confusion while running your eval code. Could you please clarify whether the completion ratio obtained from the eval_recon.py code represents the actual coverage? When I only ran it on two pieces of data, the coverage rate was 96.9375%, but visually, it didn't seem to reach 50% of the gt_mesh. Thank you for your response!

**Comment by JIANG-CX** [comment]
The completion ratio is determined by calculating the ratio of the competition metric values that are lower than 0.05m. Therefore, it can be considered as the coverage metric.

**Comment by Ubee121** [comment]
Thanks for your reply! Could you please help me understand why my actual reconstructed mesh looks like the image below, yet the coverage rate is reported as 96.9375%? I would greatly appreciate your insights. Thank you!
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/171109586/7b4669ad-63e6-43e2-92f1-3f4c44dd8f6a)
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/171109586/4b5e452d-391d-4902-99fb-c2101c5889a1)

**Comment by JIANG-CX** [comment]
In our evaluation, we assume that all frames are used. Consequently, we cull portions of the ground truth mesh based on the Octree Voxels in our method to exclude regions not visible in the input frames. 
It appears that not all frames were used in this experiment, resulting in significant culling of the ground truth mesh and causing this issue. 
If you prefer not to cull the mesh, you can change the parameter 'only_cal_has_vox' to 'false'.

**Comment by Ubee121** [comment]
It really works! Thank you for your swift response!
