### ISSUE TITLE
How to use Intel Realsense calibrated data in this particular usecase?

### ISSUE THREAD

**Issue by ShreyasKuntnal** [SYSU-STAR/H2-Mapping#41]
I have completely implemented H2-Mapping on my PC with 4070 GPU. I have calibrated intel realsense (D435i) colour camera following [Patrick Geneva sensor calibration guide](https://www.youtube.com/watch?v=BtzmsuJemgI). 
I got YAML file which contains this info of IMU calibration and camera calibration
IMU:
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/83037209/c6776c61-a4fb-46ed-b7b2-b67819d1c19d)
camera:
[camera_imu_calib3-report-imucam.pdf](https://github.com/user-attachments/files/16094316/camera_imu_calib3-report-imucam.pdf)

Then I processed these camera and IMU data to vins format using [kalib2vins](https://github.com/alploskov/kalibr2vins) package.

Finally, I got these below data:
cam0.yaml:
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/83037209/f30ab30a-8c81-49be-a2f5-c44179be5b92)

vins_config.yaml:
![image](https://github.com/SYSU-STAR/H2-Mapping/assets/83037209/c553df22-be22-4bb2-8a1b-4b75107eb2cb)

But dvins/config/ folder has mutiple config files and they have extrinsic transformation and extrinsic rotation tags.
So, how to use these OpenCV matrix in the above vins?

**Comment by ShreyasKuntnal** [comment]
@JIANG-CX Can you please help with this issue?

**Comment by JIANG-CX** [comment]
hi, I am dealing some urgent things currently. I will response your questions next week as soon as possible.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shreyas K ***@***.***>
发送时间: Friday, July 5, 2024 3:15:07 PM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: JIANG Chenxing ***@***.***>; Mention ***@***.***>
主题: Re: [SYSU-STAR/H2-Mapping] How to use Intel Realsense calibrated data in this particular usecase? (Issue #41)


@JIANG-CX<https://github.com/JIANG-CX> Can you please help with this issue?

―

**Comment by ShreyasKuntnal** [comment]
Hi, Can you please look into above issue?

**Comment by JIANG-CX** [comment]
You can follow https://github.com/HKUST-Aerial-Robotics/VINS-Mono?tab=readme-ov-file#5-run-with-your-device to write your own config, and change the "config_path" in the uav_nerf.launch
