### ISSUE TITLE
environment issue

### ISSUE THREAD

**Issue by whwh747** [SYSU-STAR/H2-Mapping#42]
I noticed that the installation of PyTorch was done before creating the virtual environment, so PyTorch is installed in the base environment, right?   Thank you！

**Comment by JIANG-CX** [comment]
The PyTorch is also required to install in the h2mapping virtual environment.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: whwhwh ***@***.***>
发送时间: Saturday, July 6, 2024 10:59:18 AM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SYSU-STAR/H2-Mapping] environment issue (Issue #42)


I noticed that the installation of PyTorch was done before creating the virtual environment, so PyTorch is installed in the base environment, right? Thank you！

―

**Comment by whwh747** [comment]
i got is，thank you very much！
