### ISSUE TITLE
请问d_pose 是否进行了更新 

### ISSUE THREAD

**Issue by zfkdsg** [SYSU-STAR/H2-Mapping#46]
作者你好 我在学习阅读你的代码过程中有些疑惑 在 run 函数中 ：
  for frame_id in progress_bar:
                data_in = self.data_stream[frame_id]
                if self.use_gt:
                    tracked_frame = RGBDFrame(*data_in[:-1], offset=self.offset, ref_pose=data_in[-1])
                else:
                    tracked_frame = RGBDFrame(*data_in[:-1], offset=self.offset, ref_pose=self.tracked_pose.clone())
                if update_pose is False:
                    tracked_frame.d_pose.requires_grad_(False)
                if tracked_frame.ref_pose.isinf().any():
                    continue
                self.mapping_step(frame_id, tracked_frame, update_pose)  
         设定了d_pose 这个参数不进行梯度计算 而在 frame.py 函数中
lass RGBDFrame(nn.Module):         #定义图片帧的类
           ........................
                self.ref_pose = ref_pose.clone().requires_grad_(False)
            self.d_pose = OptimizablePose.from_matrix(torch.eye(4, requires_grad=False, dtype=torch.float32))
        else:
            self.ref_pose = None 
同样如此 是不是说明在代码中 没有进行 位姿的反向传播更新 仅仅对sdf color  depth等内容进行了更新 谢谢

**Comment by JIANG-CX** [comment]
对，没有对pose做更新，tracking部分和mapping部分彼此独立

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zfkdsg ***@***.***>
发送时间: Friday, August 23, 2024 11:55:17 AM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SYSU-STAR/H2-Mapping] 请问d_pose 是否进行了更新 (Issue #46)


作者你好 我在学习阅读你的代码过程中有些疑惑 在 run 函数中 ：
for frame_id in progress_bar:
data_in = self.data_stream[frame_id]
if self.use_gt:
tracked_frame = RGBDFrame(*data_in[:-1], offset=self.offset, ref_pose=data_in[-1])
else:
tracked_frame = RGBDFrame(*data_in[:-1], offset=self.offset, ref_pose=self.tracked_pose.clone())
if update_pose is False:
tracked_frame.d_pose.requires_grad_(False)
if tracked_frame.ref_pose.isinf().any():
continue
self.mapping_step(frame_id, tracked_frame, update_pose)
设定了d_pose 这个参数不进行梯度计算 而在 frame.py 函数中
lass RGBDFrame(nn.Module): #定义图片帧的类
........................
self.ref_pose = ref_pose.clone().requires_grad_(False)
self.d_pose = OptimizablePose.from_matrix(torch.eye(4, requires_grad=False, dtype=torch.float32))
else:
self.ref_pose = None
同样如此 是不是说明在代码中 没有进行 位姿的反向传播更新 仅仅对sdf color depth等内容进行了更新 谢谢

―
