### ISSUE TITLE
关于mkl_random,mkl,mkl_fft,mkl-service,intel-openmp这几个库

### ISSUE THREAD

**Issue by chenghaozhangswu** [SYSU-STAR/H2-Mapping#6]
mkl_random,mkl,mkl_fft,mkl-service,intel-openmp这几个库是不是没有aarch版本，jetson上创建anaconda环境需要这几个库吗？

**Comment by JIANG-CX** [comment]
如果没有的话应该就不需要装了，这边提供的conda环境是我在x86平台导出的，可能包含了一些x86中自动装的库

**Comment by chenghaozhangswu** [comment]
好的，谢谢
